// <auto-generated />
using BíblIA.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BiBlIA.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324000000_AddMultipleTranslations")]
    partial class AddMultipleTranslations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // BuildTargetModel é usado apenas para geração de scripts SQL offline.
            // Para db.Database.Migrate() apenas o método Up() acima é executado.
        }
    }
}
